### ISSUE TITLE
LxFTPRequest.m file unsynchronized via pod install

### ISSUE THREAD

**Issue by orochi09** [DeveloperLx/LxFTPRequest#12]
I have s.dependency 'LxFTPRequest', '~> 1.0.0' and do pod install, then I found the generated LxFTPRequest.m file is different from the one in this git repo. The "resourceListRequest" function doesn't work when using the generated LxFTPRequest.m but works in the one in this git repo. 

Another problem is: for the ftp url string validation function, it doesn't allow "-" in the string, but actually my ftp server address does have "-" in the string, like "ftp://abc-def.xxx.com". Could you also fix that? Thanks!

**Comment by DeveloperLx** [comment]
fixed
