### ISSUE TITLE
NSURL with imageviewpicker not working

### ISSUE THREAD

**Issue by Geremp** [DeveloperLx/LxFTPRequest#25]
Hello,

I try to upload a video from my iphone with photolibrary :

NSURL *videoURL = [info objectForKey:UIImagePickerControllerMediaURL];

But your lib says that the localFileURL is illegal, but the path given is good.

Do you know what happen ?

**Comment by DeveloperLx** [comment]
Your path should match the regex expression "^[Ff][Ii][Ll][Ee]://?((/[=_0-9a-zA-Z%\\-]+(\\.[_0-9a-zA-Z]+)?)+(/|\\.[_0-9a-zA-Z]+)?)$", please confirm~
